### ISSUE TITLE
Updates after Review 

### ISSUE THREAD

**Issue by bms63** [pharmaverse/e2e_pk#9]
## Front Page
- [x] github icon for link to repo
- [x] have admiral come first, then metacore, metatools, xportr, sdtm last
- [x] shrink images for the packages
- [x] can remove the About Title
- [ ]

### Menu Bar
- [x] Can ADPC be the first option
- [ ]  link to core pharmaverse site

## ADPC Template
- [x] stringer should be stringr
- [x] Can it be load packages, remove space and remove comment
![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/00731ef3-0d3c-437a-8b2a-03ebcb765900)

- [x] remove `suppressWarnings` and use code chunk
- [ ] Can we make functions and packages linkable like we do in pkgdown
- [x] Eliminate space, remove comments.  I think the comment should be removed from teh code snipper and referenced in the text

![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/e83d8d80-0339-4629-8206-c215bc1e18a6)

- [x] Anyway to leverage metacore to remove this lookup table
![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/608213ee-f11b-4639-a1e3-21dae6d95b0b)

- [x] can this be itemized bullets just to break it up 
![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/a73b08e5-5bd6-45f3-b2d7-a5f0888d61ef)

- [x] this can be eliminated since we are now doing metadata!! 
![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/cbcda175-8c71-464b-84ac-20a915318b50)

- [x] Suppress messages and state the extra we are doing here (lengths, formats, etc)
![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/d57d17ba-4e96-4f5f-b3bc-3724c7bed115)

## ADPPK Template

- [x] A lot of my requests in ADPC can be carried over to ADPPK

- [x] do we need this is we have the drop_unspecified later on? 
![image](https://github.com/pharmaverse/e2e_pk/assets/10111024/0bd16999-8dcf-47bc-8183-9e055a7dcac0)

**Comment by bms63** [comment]
@jeffreyad Hey Jeff I made a pass at this - happy to discuss and make a second pass once the updates are made.

**Comment by jeffreyad** [comment]
> @jeffreyad Hey Jeff I made a pass at this - happy to discuss and make a second pass once the updates are made.

@bms63 thanks!  I'll take a look

**Comment by jeffreyad** [comment]
Hi @bms63 thanks, I think I have addressed most of the comments.  Regarding the pkgdown links, it looks like pkgdown automatically creates links.  I'm not sure if Quarto has the same functionality.  I'll continue to check this out.

https://pkgdown.r-lib.org/articles/linking.html

**Comment by jeffreyad** [comment]
Will mark as complete.
